import { readFileSync } from 'node:fs';
import ts from 'typescript';
import assert from 'node:assert/strict';
const source = readFileSync(new URL('./subtitleMatching.ts', import.meta.url), 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 } }).outputText;
const { associateSubtitles, subtitleStatus } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
const rows = ['A', 'B'].map(dir => ({ torrent_path: `${dir}/Show - 01.mkv`, file_name: 'Show - 01.mkv', show_name: 'Show', src_season: 1, src_episode: 1 }));
const file = path => ({ id: `torrent:${path}`, path, name: path.split('/').pop(), source: 'torrent' });
const same = file('A/Show - 01.chs.ass');
let result = associateSubtitles(rows, [same], {});
assert.equal(result[rows[0].torrent_path].linked[0], same);
assert.equal(subtitleStatus(result[rows[1].torrent_path]), 'missing');
const other = file('Subs/Show - 01.cht.ass');
result = associateSubtitles(rows, [other], {});
assert.equal(subtitleStatus(result[rows[0].torrent_path]), 'pending');
assert.equal(result[rows[1].torrent_path].linked.length, 0);
result = associateSubtitles(rows, [other], { [other.id]: rows[1].torrent_path });
assert.equal(result[rows[1].torrent_path].linked.length, 1);
assert.equal(result[rows[0].torrent_path].candidates.length, 0);
assert.equal(associateSubtitles(rows, [same], { [same.id]: null })[rows[0].torrent_path].linked.length, 0);
assert.equal(associateSubtitles(rows, [file('A/01.ass')], {})[rows[0].torrent_path].linked.length, 0);
const uploaded = { id: 'upload:renamed_2.ass', name: 'original.ass', path: 'renamed_2.ass', source: 'upload' };
assert.equal(associateSubtitles(rows, [same, uploaded], { [uploaded.id]: rows[0].torrent_path })[rows[0].torrent_path].linked.length, 2);
console.log('Subtitle associations: 7 scenarios passed');
